definitions:
  models.Task:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server Petstore server.
  license: {}
  title: Swagger Example API
  version: "1.0"
paths:
  /tasks/:
    get:
      description: get all tasks
      operationId: get-string-by-int
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Show a tasks
  /tasks/{id}:
    get:
      description: get task by ID
      operationId: get-task-by-int
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Task'
      summary: Get a task
swagger: "2.0"
