definitions:
  models.Task:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server Petstore server.
  license: {}
  title: Swagger Example API
  version: "1.0"
paths:
  /tasks/:
    get:
      description: get all tasks
      operationId: get-string-by-int
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Show a tasks
    post:
      consumes:
      - application/json
      description: add task
      parameters:
      - description: A task to add
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/models.Task'
          type: object
      responses:
        "201": {}
      summary: Add task
  /tasks/{id}:
    delete:
      description: delete task by ID
      parameters:
      - description: ID of task to be deleted
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200": {}
      summary: Delete a task
    get:
      description: get task by ID
      operationId: get-task-by-int
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Task'
      summary: Get a task
    put:
      consumes:
      - application/json
      description: update a task by ID
      parameters:
      - description: An ID to update
        in: path
        name: id
        required: true
        type: integer
      - description: A task to update
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/models.Task'
          type: object
      responses:
        "200": {}
      summary: Update a task
swagger: "2.0"
